### PR TITLE
Fix IE8

### PR DESCRIPTION
**Pull request by knalbandianbrightgrove**
- fix IE8 issue related from `lodash.clonedeep` as they don't support IE8 anymore

### CODE REVIEW

**Comment by CacheControl** [comment]
Thanks for the contribution @knalbandianbrightgrove 

Quick explanation on the value this feature adds: The reason deep cloning is used in this part of the code is to ensure that any time the engine runs and a `RuleResult` object is provided, the developer can do anything they want with those results, without fear of affecting the internals of the engine.  Meaning they can mutate/mutilate the `ruleResult` to their heart's content, and subsequent runs of the engine will work just fine.

I mention this because I notice in the [docs](https://github.com/jonschlinkert/clone-deep#heads-up) for the `clone-deep` library, there's a warning about cloning object instances (this jumped out at me because json-rules-engine makes heavy use of class instances).  I was a little surprised the test suite passed because I _thought_ I'd added coverage around the use of deep cloning; turned out I'd forgotten to write that test.

I went ahead and added the missing coverage to [master](https://github.com/CacheControl/json-rules-engine/blob/master/test/engine-event.test.js#L235-L252).  After merging this into the PR above, you'll notice the test will fail; this is because `clone-deep` requires a callback which specifies which properties to copy from the target object instance.

I did come across an **alternative package** called [clone](https://github.com/pvorb/clone) which _may_ do the trick; it does not explicitly claim support for ie8, but it does have monthly downloads in the tens of millions and is the dependency of several front end projects.  Installing it and using in place of `clone-deep` allows the tests to pass, but I'm not in a position to test IE8 - perhaps you could give it a try?

**Comment by knalbandianbrightgrove** [comment]
@CacheControl 

I very appreciated, thank you for the informative explanation!!

I've checked `clone` in IE8, it works, I've made another PR.

Kind regards!

**Comment by CacheControl** [comment]
@knalbandianbrightgrove great, I'll go over this one more time tonight, and merge + version if everything looks good!

**Comment by CacheControl** [comment]
@knalbandianbrightgrove this is published as **2.0.2**, thanks again for the contribution!

**Comment by knalbandianbrightgrove** [comment]
@CacheControl thank you for the awesome solution with great solution!

**Pull request merged**
