### PR TITLE
Fact paths

### PR DESCRIPTION
**Pull request by CacheControl**
Adds support for traversing an object returned from a fact.

@ctaity @slmmm - will this work for solving your use cases?

### CODE REVIEW

**Comment by slmmm** [comment]
@CacheControl Thanks for doing this!  I'll try it out :-)

**Comment by slmmm** [comment]
@CacheControl , I tested a couple of paths.
The first worked out beautifully - simple property path for example, "address.zipcode"
The second doesn't seem to be triggering - properties with depth for example,  "address.prop.test[0].zipcode".  I was attempting to trigger on empty values.

Might I be setting up the Condition incorrectly for the object?

// test object
{
    "firstName": "Good",
    "lastName": "Test",
    "ein": "123456789",
    "address": {
    	"prop": {"test": [
    		{"street": "", "zipcode": ""},
    		{"street": "", "zipcode": ""},
    		{"street": "", "zipcode": ""},
    		{"street": "", "zipcode": ""}
    		]},
        "street": "lane",
        "zipcode": "11111"
    }
}

// rule
    "conditions": {
      "any": [
        {
          "fact": "address",
          "operator": "equal",
          "value": "",
          "path": ".prop.test[0].street"
        },
        {
          "fact": "address",
          "operator": "equal",
          "value": "",
          "path": ".prop.test[0].zipcode"
        }
      ]
    }

**Comment by CacheControl** [comment]
@slmmm Thanks for taking a crack at this! Your sample looks correct, perhaps you're testing against version 1.1, which I released earlier this week?  These changes haven't been pushed to npm.

If that was the case, I've just published `1.2.0-beta` for your convenience.

If something else is going on, maybe double check against this [test](https://github.com/CacheControl/json-rules-engine/blob/514e85160ff3cacc845f32c118933a9ef54cf413/test/engine-fact.test.js#L113), which demonstrates a similar situation.

**Comment by slmmm** [comment]
Yes, you're correct.  I should have pulled rather than install from npm. 
And now after installing the 1.2.0-beta version, it DOES work wonderfully!!  THANK YOU, this will allow us to remove a few custom facts (functions) and make the rule conditions cleaner. :+1: 

A Question - how might it be possible for us to also reference this path functionality from within a custom fact where we're getting facts from a call to almanac.factValue()?

**Comment by CacheControl** [comment]
Cool, glad it works.

Regarding accessing this functionality within a custom fact - I'd like to know more about your motivations.  For example::

```js
// why would this:
engine.addFact('account-information', function (params, almanac) {
  return almanac.factValue('address', {}, '.prop.test[0].zipcode')  // path as the third arg, for example
})

// be preferable to this:
engine.addFact('account-information', function (params, almanac) {
  return almanac.factValue('address', {}).then(address => address.prop.test[0].zipcode)
})
```

**Comment by slmmm** [comment]
The preference is for dynamic rule building of its conditions.

// In this case, the fact value **reference is hard-coded**, and only changed programmatically.  This fact can only be used in one scenario in which address object has the specific path.
engine.addFact('account-information', function (params, almanac) {
  return almanac.factValue('address', {}).then(address => **address.prop.test[0].zipcode**)
})

But in our case, we are attempting to utilize generalized custom facts that allow for reuse across more than a specific object.  In order to do this, we've been using "params" to carry the various "paths" we're interested in.

As you point out though, it would be outside the scope of a "fact" to comprehend the multitude of "rules" and their varying properties like 'path'.

Thinking on this a bit more, for our current cases, we may actually be able to use the combination of the new "path" functionality and the new "custom operator" functionality to accomplish what we're doing in our generalized custom facts.
I'll try this combo approach first. :-)

**Comment by ganeshcse2991** [comment]
Hi My Fact JSON is this :
{
status: "closed"
item:{
id: 1,
model: "something"
}
}

and My Rules is :
{
            conditions: {
              all: [
                {
                  fact: "status",
                  operator: "equal",
                  value: "closed"
                }
              ]
            },
            event: {
              type: "sendEmail",
              params: {
              }
            }
}


I am getting an error while running it. Engine is throwing error that it could not convert ObjectType to String. Since JSON object item is in the fact it trying to compare it as a string to my condition.

Please help where I am doing it wrong.

**Pull request merged**
