### PR TITLE
Feature/add value pipes support

### PR DESCRIPTION
**Pull request by migzzi**
### Add support for pipes to manipulate fact values.

Here is an example of using a pipe to transform the balance currency from euros to USD and another one for applying a discount to the product.
```
const discount = 0.5;
const rule = {
    conditions: {
      all: [{
        fact: 'account',
        path: '$.balance',
        params: {
          accountType: 'eurosAccount'
        },
        pipes: [ { name: 'euroToUSD' } ],
        operator: 'greaterThanInclusive', 
        value: {
          fact: 'product',
          path: '$.price',
          pipes: [ { name: 'scale', args: [discount]}],
          params: {
            productId: 'giftCard'
          }
        }
      }]
    },
    event: { type: 'customer-can-partially-afford-gift-card' }
  }
 
 engine.addPipe('euroToUSD', (val) => val * 1.1)
```

### CODE REVIEW

**Comment by migzzi** [comment]
@CacheControl I need your review on this if you got some time.

**Comment by yoni333** [comment]
i think  this  feature is out of the scope of rule engine. it is nice to have.... but it will break the pure rule engine concept. pipes will move as to the STATE MACHINE zone

**Comment by CacheControl** [comment]
Yeah I think I agree with @yoni333. Although I appreciate the considerable work that's gone into this PR, pipes feel outside the scope of the project, and would introduce considerable runtime and debugging complexity. I think similar behavior can be achieved with the existing primitives (e.g. dynamic facts)

**Comment by CacheControl** [comment]
re-opening for visibility and to hear more opinions on this feature; I can see it being valuable for certain situations.

**Comment by chris-pardy** [comment]
@CacheControl my thought on this is that we could make the `Condition` constructor pluggable, so that it's easy to drop in custom condition classes. Additionally a way to plug in custom `Almanacs` could fill this role.

Over all what I think we should focus on for improvements is less new features and more ways to plug in new features by providing points at which other code can step in.

**Comment by chris-pardy** [comment]
@CacheControl see #356 for part of the work to support something like this. The ability to plug in custom condition classes in order to add arbitrary logic. In this case the support for pipes would need to live in the condition.

**Comment by yoni333** [comment]
in my work place we was need to add some changes in the source code in order to get data on array conditions - to know the index inside the array that  fail the condition check. so we pass and expose the "this" of the inner rule object .. 
so it is needed for better data type "Array" results.

**Pull request closed without merging**
