### PR TITLE
add package lock

### PR DESCRIPTION
**Pull request by emilefokkemanavara**
The [build](https://github.com/CacheControl/json-rules-engine/actions/runs/11873551716/job/33088503354?pr=397) fails because of recent changes around typescript-eslint. Let's stick to a version that works for us.

- Add package-lock
- Run `npm ci` instead of `npm install` in CI

### CODE REVIEW

**Comment by chris-pardy** [comment]
@emilefokkemanavara I personally use pnpm or yarn as a package manager. Curious on your thoughts of moving this to pnpm, adding a pnpm lock file etc?

**Comment by emilefokkemanavara** [comment]
@chris-pardy pnpm is fine by me. Something like this?

**Comment by chris-pardy** [comment]
@emilefokkemanavara yeah. we'll also need to update the deploy action.

**Review by chris-pardy — APPROVED** [review]

**Comment by emilefokkemanavara** [comment]
> @emilefokkemanavara yeah. we'll also need to update the deploy action.

done.

**Comment by emilefokkemanavara** [comment]
@chris-pardy this ok to merge?

**Review by chris-pardy — APPROVED** [review]

**Pull request merged**
